name: Validate and Format
run-name: "${{ github.actor }} pushed to ${{ github.ref }}"
on:
  pull_request:
    branches: 
       - main
permissions:
  contents: write
jobs:
  Validations:
    env:
      working-directory: ./terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.3
        with:
          ref: ${{ github.head_ref }}
      - name: ShellCheck
        run: |
          find . \( ! -regex '\./\.git/.*' \)  -type f -executable -print0 | xargs -0L1 shellcheck
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Terraform update and validate
        working-directory: ./terraform
        run: |
          cp ../samples/proxy-config.yaml ../config/proxy-config.yaml
          cp ../samples/vars.yaml ../config/proxy-config.yaml
          terraform init -upgrade
          terraform validate
      - name: Terraform security scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ./terraform
      - name: Update terraform documentation
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: ./terraform
          output-file: README.md
          output-method: replace
      - name: CDK Checks
        working-directory: ./cdk
        run: |
          npm install
          npm run format
          npm run lint
      - name: Commit automated formatting
        run: |
          if ! git status | grep -e '^nothing to commit, working tree clean'; then 
            git config --global user.name "$github.actor"
            git config --global user.email "$github.actor@users.noreply.github.com"
            sudo git add .
            git commit -m "Automated format updates."
            git push
          fi
