name: Validate and Format
run-name: "${{ github.actor }} pushed to ${{ github.ref_name }}"
on:
  push:
    branches: 
       - 27-add-pre-merge-checks
permissions:
  contents: write
jobs:
  Terraform:
    env:
      working-directory: ./terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.3
        with:
          ref: ${{ github.ref_name }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Terraform Checks
        working-directory: ${{ env.working-directory }}
        run: |
          cp ../samples/proxy-config.yaml ../config/proxy-config.yaml
          cp ../samples/vars.yaml ../config/proxy-config.yaml
          terraform init -upgrade
          terraform validate
      - uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ env.working-directory }}
      - uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: ${{ env.working-directory }}
          output-file: README.md
      - name: Commit terraform changes
        working-directory: ${{ env.working-directory }}
        run: |
          git config --global user.name "$github.actor"
          git config --global user.email "$github.actor@users.noreply.github.com"
          sudo git add .
          git commit -m "Automated updates generated by terraform checks."
          git push

  CDK:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.3
        with:
          ref: ${{ github.ref_name }}

      - name: CDK Checks
        working-directory: ./cdk
        run: |
          npm install
          npm run format
          npm run lint

      - name: Commit cdk changes
        id: cdkcommit
        working-directory: ./cdk
        run: |
        run: |
          git config --global user.name "$github.actor"
          git config --global user.email "$github.actor@users.noreply.github.com"
          sudo git add .
          git commit -m "Automated updates generated by cdk checks."
          git push
      