name: Validate and Format
run-name: "${{ github.actor }} pushed to ${{ github.ref_name }}"
on:
  push:
    branches: 
       - 27-add-pre-merge-checks
jobs:
  Terraform:
    env:
      working-directory: ./terraform
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup git
        run: |
          git config --global user.name "$github.actor"
          git config --global user.email "$github.actor@users.noreply.github.com"
      - name: Checkout $github.ref_name
        uses: actions/checkout@v3.5.3
        with:
          ref: ${{ github.ref_name }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Terraform Checks
        working-directory: ${{ env.working-directory }}
        run: |
          cp ../samples/proxy-config.yaml ../config/proxy-config.yaml
          cp ../samples/vars.yaml ../config/proxy-config.yaml
          terraform init -upgrade
          terraform validate
      - uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ env.working-directory }}
      - uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: ${{ env.working-directory }}
          output-file: README.md
      - name: Commit terraform changes
        run: |
          sudo git add terraform/
          git commit -m "Automated updates generated by terraform checks."
          git push

  # CDK:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Setup
  #       uses: actions/checkout@v3.5.3
  #       with:
  #         ref: ${{ github.ref_name }}
  #     - run: |
  #         git config --global user.name "$github.actor"
  #         git config --global user.email "$github.actor@users.noreply.github.com"
  #         chown -R "${USER:-$(id -un)}" .
  #     - name: CDK Checks
  #       working-directory: ./cdk
  #       run: |
  #         npm install
  #         npm run format
  #         npm run lint
  #     - name: Commit cdk changes
  #       id: cdkcommit
  #       working-directory: ./cdk
  #       run: |
  #         git add .
  #         git commit -m "Automated updates generated by cdk checks."

  #     - name: Push automated updates.
  #       run: git push
      